/**
 * generate-seed.ts
 * JSON 데이터 파일(tier/crew/fa/tournament)을 읽어 sql/002_seed_data.sql을 생성한다.
 *
 * 사용법: bun run scripts/generate-seed.ts
 */

import { join } from "node:path";

const DATA_DIR = join(import.meta.dirname, "..", "data");
const OUT_PATH = join(import.meta.dirname, "..", "sql", "002_seed_data.sql");

// ─── Load JSON ───
const tierData = await Bun.file(join(DATA_DIR, "tier-data.json")).json();
const crewData = await Bun.file(join(DATA_DIR, "crew-data.json")).json();
const faData = await Bun.file(join(DATA_DIR, "fa-data.json")).json();
const tournamentData = await Bun.file(join(DATA_DIR, "tournament-data.json")).json();

// ─── Helpers ───
function esc(s: string): string {
  return s.replace(/'/g, "''");
}

// ─── 종족 수정 맵 (crew-data._race_corrections) ───
const raceCorrections = new Map<string, string>();
for (const c of crewData._race_corrections.corrections) {
  raceCorrections.set(c.nickname, c.new_race);
}

// ─── 닉네임 불일치 매핑 (티어표 닉네임 → 크루 닉네임) ───
const nameDiscrepancy = new Map<string, string>();
for (const d of crewData._race_corrections.name_discrepancy) {
  nameDiscrepancy.set(d.tier_name, d.crew_name);
}

// ─── 여캠 티어에 있지만 남자인 선수 ───
const maleInFemaleTier = new Set<string>(
  faData._male_in_female_tier.map((p: { nickname: string }) => p.nickname),
);

// ─── FA 선수 목록 ───
const faSet = new Set<string>();
for (const p of faData.male_fa) faSet.add(p.nickname);
for (const p of faData.female_fa) faSet.add(p.nickname);

// ─── 크루 멤버 닉네임 → 크루명 매핑 ───
// 크루 데이터의 닉네임이 티어표와 다를 수 있으므로 역방향 매핑도 필요
const crewMemberMap = new Map<string, string>(); // 닉네임 → 크루명
const crewNames = new Set<string>();

for (const crew of crewData.crews) {
  crewNames.add(crew.name);
  for (const member of crew.members) {
    crewMemberMap.set(member.nickname, crew.name);
  }
}

// 역방향: 크루 닉네임이 티어표 닉네임과 다른 경우 매핑
for (const d of crewData._race_corrections.name_discrepancy) {
  // tier_name은 티어표 닉네임, crew_name은 크루 데이터 닉네임
  const crewName = crewMemberMap.get(d.crew_name);
  if (crewName) {
    crewMemberMap.set(d.tier_name, crewName);
  }
}

// ─── 비활성 크루 (대회 우승만 있고 현재 해체) ───
const inactiveCrewNames = new Set<string>();
for (const t of tournamentData.tournaments) {
  if (t.winner && !crewNames.has(t.winner)) {
    inactiveCrewNames.add(t.winner);
  }
}

// ─── 크루에만 있는 신규 플레이어 (티어표에 없음) ───
interface NewPlayer {
  nickname: string;
  tier: string;
  race: string;
  source: string;
}
const newPlayers: NewPlayer[] = crewData._race_corrections.new_players;

// ─── 티어표에서 전체 플레이어 수집 ───
interface PlayerEntry {
  nickname: string;
  race: string;
  tier: string;
  gender: string;
  tag: string | null;
  is_fa: boolean;
  crew_name: string | null;
  status: string;
}

const players: PlayerEntry[] = [];
const seenNicknames = new Set<string>();

for (const tierGroup of tierData.tiers) {
  for (const p of tierGroup.players) {
    const nickname = p.nickname;
    if (seenNicknames.has(nickname)) continue;
    seenNicknames.add(nickname);

    // 종족: 크루 데이터 수정사항 우선
    const race = raceCorrections.get(nickname) ?? p.race;

    // 성별: God~Spade = M, 0~Baby = F (예외: maleInFemaleTier)
    const tierGender = tierGroup.gender as string;
    const gender = maleInFemaleTier.has(nickname) ? "M" : tierGender;

    // 태그
    const tag: string | null = p.tag ?? null;

    // 상태
    const status = tag === "inactive" ? "inactive" : "active";

    // FA 여부
    const is_fa = faSet.has(nickname);

    // 크루 매칭
    let crew_name: string | null = null;
    if (!is_fa) {
      crew_name = crewMemberMap.get(nickname) ?? null;
    }

    players.push({ nickname, race, tier: tierGroup.tier, gender, tag, is_fa, crew_name, status });
  }
}

// 크루에만 있는 신규 플레이어 추가
for (const np of newPlayers) {
  if (seenNicknames.has(np.nickname)) continue;
  seenNicknames.add(np.nickname);

  const tierGender = ["God", "King", "Jack", "Joker", "Spade"].includes(np.tier) ? "M" : "F";
  const gender = maleInFemaleTier.has(np.nickname) ? "M" : tierGender;

  players.push({
    nickname: np.nickname,
    race: np.race,
    tier: np.tier,
    gender,
    tag: null,
    is_fa: false,
    crew_name: crewMemberMap.get(np.nickname) ?? np.source,
    status: "active",
  });
}

// ─── SQL 생성 ───
const lines: string[] = [];
lines.push("-- StarUniv Seed Data (auto-generated by scripts/generate-seed.ts)");
lines.push(`-- Generated: ${new Date().toISOString()}`);
lines.push(`-- Tier version: ${tierData.version} (${tierData.updated_at})`);
lines.push("");
lines.push("BEGIN;");
lines.push("");

// 기존 데이터 정리
lines.push("-- Clean existing data");
lines.push("DELETE FROM players;");
lines.push("DELETE FROM tournaments;");
lines.push("DELETE FROM crews;");
lines.push("DELETE FROM tier_versions;");
lines.push("");

// 시퀀스 리셋
lines.push("-- Reset sequences");
lines.push("ALTER SEQUENCE players_id_seq RESTART WITH 1;");
lines.push("ALTER SEQUENCE crews_id_seq RESTART WITH 1;");
lines.push("ALTER SEQUENCE tournaments_id_seq RESTART WITH 1;");
lines.push("ALTER SEQUENCE tier_versions_id_seq RESTART WITH 1;");
lines.push("");

// 크루 삽입
lines.push("-- ─── Crews ───");
const allCrewNames = [...crewNames, ...inactiveCrewNames];
const crewIdMap = new Map<string, number>();
let crewId = 1;

// 활성 크루
for (const crew of crewData.crews) {
  crewIdMap.set(crew.name, crewId);
  lines.push(
    `INSERT INTO crews (id, name, is_active) VALUES (${crewId}, '${esc(crew.name)}', true);`,
  );
  crewId++;
}

// 비활성 크루 (대회 우승 이력만)
for (const name of inactiveCrewNames) {
  crewIdMap.set(name, crewId);
  lines.push(`INSERT INTO crews (id, name, is_active) VALUES (${crewId}, '${esc(name)}', false);`);
  crewId++;
}

lines.push("");

// 플레이어 삽입
lines.push("-- ─── Players ───");
let playerId = 1;
for (const p of players) {
  const crewIdVal = p.crew_name ? crewIdMap.get(p.crew_name) : null;
  const crewIdStr = crewIdVal ? String(crewIdVal) : "NULL";
  const tagStr = p.tag ? `'${esc(p.tag)}'` : "NULL";
  lines.push(
    `INSERT INTO players (id, nickname, race, tier, gender, crew_id, is_fa, tag, status) VALUES (${playerId}, '${esc(p.nickname)}', '${p.race}', '${esc(p.tier)}', '${p.gender}', ${crewIdStr}, ${p.is_fa}, ${tagStr}, '${p.status}');`,
  );
  playerId++;
}
lines.push("");

// 대회 삽입
lines.push("-- ─── Tournaments ───");
let tournamentId = 1;
for (const t of tournamentData.tournaments) {
  const winnerCrewId = t.winner ? crewIdMap.get(t.winner) : null;
  const winnerStr = winnerCrewId ? String(winnerCrewId) : "NULL";
  const statusStr = t.status === "ongoing" ? "ongoing" : "completed";
  lines.push(
    `INSERT INTO tournaments (id, name, year, winner_crew_id, status) VALUES (${tournamentId}, '${esc(t.name)}', ${t.year}, ${winnerStr}, '${statusStr}');`,
  );
  tournamentId++;
}
lines.push("");

// 티어 버전 삽입
lines.push("-- ─── Tier Version ───");
lines.push(
  `INSERT INTO tier_versions (version, released_at, notes) VALUES ('${esc(tierData.version)}', '${tierData.updated_at}', NULL);`,
);
lines.push("");

lines.push("COMMIT;");
lines.push("");

// 파일 쓰기
await Bun.write(OUT_PATH, lines.join("\n"));

// 통계 출력
const activePlayers = players.filter((p) => p.status === "active");
const malePlayers = players.filter((p) => p.gender === "M");
const femalePlayers = players.filter((p) => p.gender === "F");
const faPlayers = players.filter((p) => p.is_fa);
const crewPlayers = players.filter((p) => p.crew_name !== null);

console.log("=== generate-seed.ts ===");
console.log(`Output: ${OUT_PATH}`);
console.log(
  `Crews: ${crewNames.size} active + ${inactiveCrewNames.size} inactive = ${allCrewNames.length}`,
);
console.log(`Players: ${players.length} total (${activePlayers.length} active)`);
console.log(`  Male: ${malePlayers.length}, Female: ${femalePlayers.length}`);
console.log(`  FA: ${faPlayers.length}, Crew: ${crewPlayers.length}`);
console.log(`Tournaments: ${tournamentData.tournaments.length}`);
console.log(`Tier version: ${tierData.version}`);
