-- 003: soop_id, profile_image 컬럼 추가 및 닉네임 수정
-- Generated from CNine API (https://preview.cnine.kr/api/v2/p/starcraft/soop/player)

BEGIN;

-- ─── 컬럼 추가 ───
ALTER TABLE players ADD COLUMN IF NOT EXISTS soop_id TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS profile_image TEXT;

-- ─── 닉네임 수정 (씨나인 API 기준) ───
UPDATE players SET nickname = '져지현' WHERE nickname = '저지현';
UPDATE players SET nickname = '저그맨박성준' WHERE nickname = '박성준2';
UPDATE players SET nickname = '히엉' WHERE nickname = '히영';
UPDATE players SET nickname = '꼬니부깅' WHERE nickname = '꼬니부킹';
UPDATE players SET nickname = '뽀누나' WHERE nickname = '옆집뽀누나농떼르만';
UPDATE players SET nickname = '으냉이' WHERE nickname = '으냥이';
UPDATE players SET nickname = '팥순' WHERE nickname = '팔순';
UPDATE players SET nickname = '경콩' WHERE nickname = '경콩이';
UPDATE players SET nickname = '쟈닌' WHERE nickname = '자닌';
UPDATE players SET nickname = '하루묭' WHERE nickname = '하루몽';
UPDATE players SET nickname = '이주헌' WHERE nickname = '이주현';
UPDATE players SET nickname = '밍또얌' WHERE nickname = '밍또암';
UPDATE players SET nickname = '구쁘' WHERE nickname = '구쁜';
UPDATE players SET nickname = '안나' WHERE nickname = '맹꽁안나';
UPDATE players SET nickname = '헤요이' WHERE nickname = '혜요이';
UPDATE players SET nickname = '박쭈이' WHERE nickname = '박쮸이';
UPDATE players SET nickname = '유녜' WHERE nickname = '유네';
UPDATE players SET nickname = '김쵸아' WHERE nickname = '김초아';
UPDATE players SET nickname = '땃쥐' WHERE nickname = '맞쥐';
UPDATE players SET nickname = '디임' WHERE nickname = '다잎';
-- ─── 중복 삭제: 허밍 = 히댕 동일인물 ───
DELETE FROM players WHERE nickname = '허밍';

-- ─── 중복 삭제: 달그락영주 = 김영주 동일인물 ───
DELETE FROM players WHERE nickname = '달그락영주';

-- ─── 신규 추가: 농떼르만 ───
SELECT setval('players_id_seq', (SELECT MAX(id) FROM players));
INSERT INTO players (nickname, race, tier, gender, is_fa, status) VALUES ('농떼르만', 'T', 'Spade', 'M', false, 'active');

-- ─── soop_id, profile_image 업데이트 ───
UPDATE players SET soop_id = 'hby0724', profile_image = '//profile.img.sooplive.co.kr/LOGO/hb/hby0724/hby0724.jpg' WHERE nickname = '황병영';
UPDATE players SET soop_id = 'scv6256', profile_image = '//profile.img.sooplive.co.kr/LOGO/sc/scv6256/scv6256.jpg' WHERE nickname = '이재호';
UPDATE players SET soop_id = 'yoo376', profile_image = '//profile.img.sooplive.co.kr/LOGO/yo/yoo376/yoo376.jpg' WHERE nickname = '유영진';
UPDATE players SET soop_id = 'byflash', profile_image = '//profile.img.sooplive.co.kr/LOGO/by/byflash/byflash.jpg' WHERE nickname = '이영호';
UPDATE players SET soop_id = 'sharpragu', profile_image = '//profile.img.sooplive.co.kr/LOGO/sh/sharpragu/sharpragu.jpg' WHERE nickname = '조기석';
UPDATE players SET soop_id = 'rfvtgb778', profile_image = '//profile.img.sooplive.co.kr/LOGO/rf/rfvtgb778/rfvtgb778.jpg' WHERE nickname = '이영웅';
UPDATE players SET soop_id = 'ho1godme', profile_image = '//profile.img.sooplive.co.kr/LOGO/ho/ho1godme/ho1godme.jpg' WHERE nickname = '김지성';
UPDATE players SET soop_id = 'neverdieyj', profile_image = '//profile.img.sooplive.co.kr/LOGO/ne/neverdieyj/neverdieyj.jpg' WHERE nickname = '정영재';
UPDATE players SET soop_id = 'ghtjs3833', profile_image = '//profile.img.sooplive.co.kr/LOGO/gh/ghtjs3833/ghtjs3833.jpg' WHERE nickname = '최호선';
UPDATE players SET soop_id = 'thakzkf', profile_image = '//profile.img.sooplive.co.kr/LOGO/th/thakzkf/thakzkf.jpg' WHERE nickname = '짭제';
UPDATE players SET soop_id = 'dpfgc3', profile_image = '//profile.img.sooplive.co.kr/LOGO/dp/dpfgc3/dpfgc3.jpg' WHERE nickname = '홍구';
UPDATE players SET soop_id = 'momo130', profile_image = '//profile.img.sooplive.co.kr/LOGO/mo/momo130/momo130.jpg' WHERE nickname = '김정우';
UPDATE players SET soop_id = 'minchul', profile_image = '//profile.img.sooplive.co.kr/LOGO/mi/minchul/minchul.jpg' WHERE nickname = '김민철';
UPDATE players SET soop_id = 'kimmyungwun', profile_image = '//profile.img.sooplive.co.kr/LOGO/ki/kimmyungwun/kimmyungwun.jpg' WHERE nickname = '김명운';
UPDATE players SET soop_id = 'jaedong23', profile_image = '//profile.img.sooplive.co.kr/LOGO/ja/jaedong23/jaedong23.jpg' WHERE nickname = '이제동';
UPDATE players SET soop_id = 'byhero', profile_image = '//profile.img.sooplive.co.kr/LOGO/by/byhero/byhero.jpg' WHERE nickname = '조일장';
UPDATE players SET soop_id = 'tjdeosks', profile_image = '//profile.img.sooplive.co.kr/LOGO/tj/tjdeosks/tjdeosks.jpg' WHERE nickname = '김성대';
UPDATE players SET soop_id = 'tmsh401', profile_image = '//profile.img.sooplive.co.kr/LOGO/tm/tmsh401/tmsh401.jpg' WHERE nickname = '장윤철';
UPDATE players SET soop_id = 'rlaxordyd', profile_image = '//profile.img.sooplive.co.kr/LOGO/rl/rlaxordyd/rlaxordyd.jpg' WHERE nickname = '김택용';
UPDATE players SET soop_id = 'wodnrdldia', profile_image = '//profile.img.sooplive.co.kr/LOGO/wo/wodnrdldia/wodnrdldia.jpg' WHERE nickname = '도재욱';
UPDATE players SET soop_id = 'bye1013', profile_image = '//profile.img.sooplive.co.kr/LOGO/by/bye1013/bye1013.jpg' WHERE nickname = '변현제';
UPDATE players SET soop_id = 'ioioiobb', profile_image = '//profile.img.sooplive.co.kr/LOGO/io/ioioiobb/ioioiobb.jpg' WHERE nickname = '정윤종';
UPDATE players SET soop_id = 'cksgmldbs', profile_image = '//profile.img.sooplive.co.kr/LOGO/ck/cksgmldbs/cksgmldbs.jpg' WHERE nickname = '몽군';
UPDATE players SET soop_id = 'peros777', profile_image = '//profile.img.sooplive.co.kr/LOGO/pe/peros777/peros777.jpg' WHERE nickname = '박성균';
UPDATE players SET soop_id = 'hoonykkk', profile_image = '//profile.img.sooplive.co.kr/LOGO/ho/hoonykkk/hoonykkk.jpg' WHERE nickname = '김태영';
UPDATE players SET soop_id = 'rladuddo99', profile_image = '//profile.img.sooplive.co.kr/LOGO/rl/rladuddo99/rladuddo99.jpg' WHERE nickname = '구성훈';
UPDATE players SET soop_id = 'onlysibar', profile_image = '//profile.img.sooplive.co.kr/LOGO/on/onlysibar/onlysibar.jpg' WHERE nickname = '샤이니';
UPDATE players SET soop_id = 'kkmkhh1234', profile_image = '//profile.img.sooplive.co.kr/LOGO/kk/kkmkhh1234/kkmkhh1234.jpg' WHERE nickname = '김경모';
UPDATE players SET soop_id = 'h78ert', profile_image = '//profile.img.sooplive.co.kr/LOGO/h7/h78ert/h78ert.jpg' WHERE nickname = '박준오';
UPDATE players SET soop_id = 'lyh8808', profile_image = '//profile.img.sooplive.co.kr/LOGO/ly/lyh8808/lyh8808.jpg' WHERE nickname = '이영한';
UPDATE players SET soop_id = 'gnsl418', profile_image = '//profile.img.sooplive.co.kr/LOGO/gn/gnsl418/gnsl418.jpg' WHERE nickname = '이예훈';
UPDATE players SET soop_id = 'bts150', profile_image = '//profile.img.sooplive.co.kr/LOGO/bt/bts150/bts150.jpg' WHERE nickname = '방태수';
UPDATE players SET soop_id = 'koreasbg', profile_image = '//profile.img.sooplive.co.kr/LOGO/ko/koreasbg/koreasbg.jpg' WHERE nickname = '송병구';
UPDATE players SET soop_id = 'jk890202', profile_image = '//profile.img.sooplive.co.kr/LOGO/jk/jk890202/jk890202.jpg' WHERE nickname = '김윤중';
UPDATE players SET soop_id = 'snfjdro369', profile_image = '//profile.img.sooplive.co.kr/LOGO/sn/snfjdro369/snfjdro369.jpg' WHERE nickname = '윤수철';
UPDATE players SET soop_id = 'jihoon002', profile_image = '//profile.img.sooplive.co.kr/LOGO/ji/jihoon002/jihoon002.jpg' WHERE nickname = '박수범';
UPDATE players SET soop_id = 'dbsdydx', profile_image = '//profile.img.sooplive.co.kr/LOGO/db/dbsdydx/dbsdydx.jpg' WHERE nickname = '윤용태';
UPDATE players SET soop_id = 'scan1014', profile_image = '//profile.img.sooplive.co.kr/LOGO/sc/scan1014/scan1014.jpg' WHERE nickname = '유승곤';
UPDATE players SET soop_id = 'zealot0846', profile_image = '//profile.img.sooplive.co.kr/LOGO/ze/zealot0846/zealot0846.jpg' WHERE nickname = '원선재';
UPDATE players SET soop_id = 'hongduck9737', profile_image = '//profile.img.sooplive.co.kr/LOGO/ho/hongduck9737/hongduck9737.jpg' WHERE nickname = '홍덕';
UPDATE players SET soop_id = 'palko1', profile_image = '//profile.img.sooplive.co.kr/LOGO/pa/palko1/palko1.jpg' WHERE nickname = '신상문';
UPDATE players SET soop_id = 'firebathero', profile_image = '//profile.img.sooplive.co.kr/LOGO/fi/firebathero/firebathero.jpg' WHERE nickname = '흑운장';
UPDATE players SET soop_id = 'organ333', profile_image = '//profile.img.sooplive.co.kr/LOGO/or/organ333/organ333.jpg' WHERE nickname = '임진묵';
UPDATE players SET soop_id = 'rondobba', profile_image = '//profile.img.sooplive.co.kr/LOGO/ro/rondobba/rondobba.jpg' WHERE nickname = '지동원';
UPDATE players SET soop_id = 'shyshy123', profile_image = '//profile.img.sooplive.co.kr/LOGO/sh/shyshy123/shyshy123.jpg' WHERE nickname = '김영진';
UPDATE players SET soop_id = 'wjdalsrl95', profile_image = '//profile.img.sooplive.co.kr/LOGO/wj/wjdalsrl95/wjdalsrl95.jpg' WHERE nickname = '정민기';
UPDATE players SET soop_id = 'bhy95', profile_image = '//profile.img.sooplive.co.kr/LOGO/bh/bhy95/bhy95.jpg' WHERE nickname = '배호딱';
UPDATE players SET soop_id = 'rlarnfk24', profile_image = '//profile.img.sooplive.co.kr/LOGO/rl/rlarnfk24/rlarnfk24.jpg' WHERE nickname = '만두호성';
UPDATE players SET soop_id = 'brainzerg7', profile_image = '//profile.img.sooplive.co.kr/LOGO/br/brainzerg7/brainzerg7.jpg' WHERE nickname = '김윤환';
UPDATE players SET soop_id = 'understay', profile_image = '//profile.img.sooplive.co.kr/LOGO/un/understay/understay.jpg' WHERE nickname = '고석현';
UPDATE players SET soop_id = 'jackpot', profile_image = '//profile.img.sooplive.co.kr/LOGO/ja/jackpot/jackpot.jpg' WHERE nickname = '이창우';
UPDATE players SET soop_id = 'rlekfu6', profile_image = '//profile.img.sooplive.co.kr/LOGO/rl/rlekfu6/rlekfu6.jpg' WHERE nickname = '박재혁';
UPDATE players SET soop_id = 'djdbstn', profile_image = '//profile.img.sooplive.co.kr/LOGO/dj/djdbstn/djdbstn.jpg' WHERE nickname = '어윤수';
UPDATE players SET soop_id = 'bwstar', profile_image = '//profile.img.sooplive.co.kr/LOGO/bw/bwstar/bwstar.jpg' WHERE nickname = '배병우';
UPDATE players SET soop_id = 'goodzerg', profile_image = '//profile.img.sooplive.co.kr/LOGO/go/goodzerg/goodzerg.jpg' WHERE nickname = '배성흠';
UPDATE players SET soop_id = 'dgh9641', profile_image = '//profile.img.sooplive.co.kr/LOGO/dg/dgh9641/dgh9641.jpg' WHERE nickname = '김병수';
UPDATE players SET soop_id = 'jh3697', profile_image = '//profile.img.sooplive.co.kr/LOGO/jh/jh3697/jh3697.jpg' WHERE nickname = '서문지훈';
UPDATE players SET soop_id = 'mwhdgus', profile_image = '//profile.img.sooplive.co.kr/LOGO/mw/mwhdgus/mwhdgus.jpg' WHERE nickname = '윤진규';
UPDATE players SET soop_id = 'wnsgur2da', profile_image = '//profile.img.sooplive.co.kr/LOGO/wn/wnsgur2da/wnsgur2da.jpg' WHERE nickname = '얍삽e';
UPDATE players SET soop_id = 'kss33325', profile_image = '//profile.img.sooplive.co.kr/LOGO/ks/kss33325/kss33325.jpg' WHERE nickname = '김수식';
UPDATE players SET soop_id = 'yuambo', profile_image = '//profile.img.sooplive.co.kr/LOGO/yu/yuambo/yuambo.jpg' WHERE nickname = '염보성';
UPDATE players SET soop_id = 'rudals5467', profile_image = '//profile.img.sooplive.co.kr/LOGO/ru/rudals5467/rudals5467.jpg' WHERE nickname = '이경민';
UPDATE players SET soop_id = 'rlatldgus', profile_image = '//profile.img.sooplive.co.kr/LOGO/rl/rlatldgus/rlatldgus.jpg' WHERE nickname = '오메킴';
UPDATE players SET soop_id = 'paralyze92', profile_image = '//profile.img.sooplive.co.kr/LOGO/pa/paralyze92/paralyze92.jpg' WHERE nickname = '정경두';
UPDATE players SET soop_id = 'jyh8610', profile_image = '//profile.img.sooplive.co.kr/LOGO/jy/jyh8610/jyh8610.jpg' WHERE nickname = '진영화';
UPDATE players SET soop_id = 'bumsoo552', profile_image = '//profile.img.sooplive.co.kr/LOGO/bu/bumsoo552/bumsoo552.jpg' WHERE nickname = '김범수';
UPDATE players SET soop_id = 'jmc06170', profile_image = '//profile.img.sooplive.co.kr/LOGO/jm/jmc06170/jmc06170.jpg' WHERE nickname = '왜냐맨';
UPDATE players SET soop_id = 'rnjsgurwls15', profile_image = '//profile.img.sooplive.co.kr/LOGO/rn/rnjsgurwls15/rnjsgurwls15.jpg' WHERE nickname = '권혁진';
UPDATE players SET soop_id = 'ksmo54', profile_image = '//profile.img.sooplive.co.kr/LOGO/ks/ksmo54/ksmo54.jpg' WHERE nickname = '구라미스';
UPDATE players SET soop_id = 'lky6407', profile_image = '//profile.img.sooplive.co.kr/LOGO/lk/lky6407/lky6407.jpg' WHERE nickname = '프발';
UPDATE players SET soop_id = 'wonjoon1814', profile_image = '//profile.img.sooplive.co.kr/LOGO/wo/wonjoon1814/wonjoon1814.jpg' WHERE nickname = '원지훈';
UPDATE players SET soop_id = 'tjr2440', profile_image = '//profile.img.sooplive.co.kr/LOGO/tj/tjr2440/tjr2440.jpg' WHERE nickname = '김봉실';
UPDATE players SET soop_id = 'toozi0317', profile_image = '//profile.img.sooplive.co.kr/LOGO/to/toozi0317/toozi0317.jpg' WHERE nickname = '이인극';
UPDATE players SET soop_id = 'daegalheo', profile_image = '//profile.img.sooplive.co.kr/LOGO/da/daegalheo/daegalheo.jpg' WHERE nickname = '허유';
UPDATE players SET soop_id = 'quaestor1', profile_image = '//profile.img.sooplive.co.kr/LOGO/qu/quaestor1/quaestor1.jpg' WHERE nickname = '져지현';
UPDATE players SET soop_id = 'byspire', profile_image = '//profile.img.sooplive.co.kr/LOGO/by/byspire/byspire.jpg' WHERE nickname = '김상곤';
UPDATE players SET soop_id = 'ckmin706', profile_image = '//profile.img.sooplive.co.kr/LOGO/ck/ckmin706/ckmin706.jpg' WHERE nickname = '민찬기';
UPDATE players SET soop_id = 'dmk1212', profile_image = '//profile.img.sooplive.co.kr/LOGO/dm/dmk1212/dmk1212.jpg' WHERE nickname = '액션구드론';
UPDATE players SET soop_id = 'spark123', profile_image = '//profile.img.sooplive.co.kr/LOGO/sp/spark123/spark123.jpg' WHERE nickname = '인치호';
UPDATE players SET soop_id = 'isangwk', profile_image = '//profile.img.sooplive.co.kr/LOGO/is/isangwk/isangwk.jpg' WHERE nickname = '전상욱';
UPDATE players SET soop_id = 'ndudska620', profile_image = '//profile.img.sooplive.co.kr/LOGO/nd/ndudska620/ndudska620.jpg' WHERE nickname = '김영주';
UPDATE players SET soop_id = 'killkg2', profile_image = '//profile.img.sooplive.co.kr/LOGO/ki/killkg2/killkg2.jpg' WHERE nickname = '김건욱';
UPDATE players SET soop_id = 'daehan7224', profile_image = '//profile.img.sooplive.co.kr/LOGO/da/daehan7224/daehan7224.jpg' WHERE nickname = '김대한';
UPDATE players SET soop_id = 'qndnd12', profile_image = '//profile.img.sooplive.co.kr/LOGO/qn/qndnd12/qndnd12.jpg' WHERE nickname = '김기덕';
UPDATE players SET soop_id = 'dohyeon97', profile_image = '//profile.img.sooplive.co.kr/LOGO/do/dohyeon97/dohyeon97.jpg' WHERE nickname = '선우도현';
UPDATE players SET soop_id = 'y1026', profile_image = '//profile.img.sooplive.co.kr/LOGO/y1/y1026/y1026.jpg' WHERE nickname = '철구';
UPDATE players SET soop_id = 'zealotmaru', profile_image = '//profile.img.sooplive.co.kr/LOGO/ze/zealotmaru/zealotmaru.jpg' WHERE nickname = '킁식';
UPDATE players SET soop_id = 'skygkrtn', profile_image = '//profile.img.sooplive.co.kr/LOGO/sk/skygkrtn/skygkrtn.jpg' WHERE nickname = '김학수';
UPDATE players SET soop_id = 'jou1025', profile_image = '//profile.img.sooplive.co.kr/LOGO/jo/jou1025/jou1025.jpg' WHERE nickname = '라박이';
UPDATE players SET soop_id = 'cksdnddldhkd', profile_image = '//profile.img.sooplive.co.kr/LOGO/ck/cksdnddldhkd/cksdnddldhkd.jpg' WHERE nickname = '손찬웅';
UPDATE players SET soop_id = 'vhrtmspt', profile_image = '//profile.img.sooplive.co.kr/LOGO/vh/vhrtmspt/vhrtmspt.jpg' WHERE nickname = '김민우';
UPDATE players SET soop_id = 'jhyhlli123', profile_image = '//profile.img.sooplive.co.kr/LOGO/jh/jhyhlli123/jhyhlli123.jpg' WHERE nickname = '박준혁';
UPDATE players SET soop_id = 'parkjaehyeon', profile_image = '//profile.img.sooplive.co.kr/LOGO/pa/parkjaehyeon/parkjaehyeon.jpg' WHERE nickname = '쿰신';
UPDATE players SET soop_id = 'khy12088wsss', profile_image = '//profile.img.sooplive.co.kr/LOGO/kh/khy12088wsss/khy12088wsss.jpg' WHERE nickname = '쿨지지';
UPDATE players SET soop_id = 'wjswpalssla1', profile_image = '//profile.img.sooplive.co.kr/LOGO/wj/wjswpalssla1/wjswpalssla1.jpg' WHERE nickname = '전제민';
UPDATE players SET soop_id = 'qhkrwns12', profile_image = '//profile.img.sooplive.co.kr/LOGO/qh/qhkrwns12/qhkrwns12.jpg' WHERE nickname = '미동미동';
UPDATE players SET soop_id = 'comcmxx', profile_image = '//profile.img.sooplive.co.kr/LOGO/co/comcmxx/comcmxx.jpg' WHERE nickname = '윤준석';
UPDATE players SET soop_id = 'aghhi', profile_image = '//profile.img.sooplive.co.kr/LOGO/ag/aghhi/aghhi.jpg' WHERE nickname = '안기효';
UPDATE players SET soop_id = 'arinbbidol', profile_image = '//profile.img.sooplive.co.kr/LOGO/ar/arinbbidol/arinbbidol.jpg' WHERE nickname = '기뉴다';
UPDATE players SET soop_id = 'byromantic', profile_image = '//profile.img.sooplive.co.kr/LOGO/by/byromantic/byromantic.jpg' WHERE nickname = '최재성';
UPDATE players SET soop_id = 'tjdwnls123', profile_image = '//profile.img.sooplive.co.kr/LOGO/tj/tjdwnls123/tjdwnls123.jpg' WHERE nickname = '박성진';
UPDATE players SET soop_id = 'nada11200', profile_image = '//profile.img.sooplive.co.kr/LOGO/na/nada11200/nada11200.jpg' WHERE nickname = '이윤열';
UPDATE players SET soop_id = 'k1s2s3', profile_image = '//profile.img.sooplive.co.kr/LOGO/k1/k1s2s3/k1s2s3.jpg' WHERE nickname = '김상수';
UPDATE players SET soop_id = 'john06911', profile_image = '//profile.img.sooplive.co.kr/LOGO/jo/john06911/john06911.jpg' WHERE nickname = '이완';
UPDATE players SET soop_id = 'skarbwhgc', profile_image = '//profile.img.sooplive.co.kr/LOGO/sk/skarbwhgc/skarbwhgc.jpg' WHERE nickname = '팔레트';
UPDATE players SET soop_id = 'dbrbals', profile_image = '//profile.img.sooplive.co.kr/LOGO/db/dbrbals/dbrbals.jpg' WHERE nickname = '초난강';
UPDATE players SET soop_id = 'cztaemin', profile_image = '//profile.img.sooplive.co.kr/LOGO/cz/cztaemin/cztaemin.jpg' WHERE nickname = '박태민';
UPDATE players SET soop_id = 'julyzerg', profile_image = '//profile.img.sooplive.co.kr/LOGO/ju/julyzerg/julyzerg.jpg' WHERE nickname = '박성준';
UPDATE players SET soop_id = 'jun10280', profile_image = '//profile.img.sooplive.co.kr/LOGO/ju/jun10280/jun10280.jpg' WHERE nickname = '저그맨박성준';
UPDATE players SET soop_id = 'leegang7', profile_image = '//profile.img.sooplive.co.kr/LOGO/le/leegang7/leegang7.jpg' WHERE nickname = '초롱초롱';
UPDATE players SET soop_id = 'khjkzzzz', profile_image = '//profile.img.sooplive.co.kr/LOGO/kh/khjkzzzz/khjkzzzz.jpg' WHERE nickname = '카권';
UPDATE players SET soop_id = 'askl021', profile_image = '//profile.img.sooplive.co.kr/LOGO/as/askl021/askl021.jpg' WHERE nickname = '빡죠스';
UPDATE players SET soop_id = 'minyoo3972', profile_image = '//profile.img.sooplive.co.kr/LOGO/mi/minyoo3972/minyoo3972.jpg' WHERE nickname = '유민';
UPDATE players SET soop_id = 'ywww123', profile_image = '//profile.img.sooplive.co.kr/LOGO/yw/ywww123/ywww123.jpg' WHERE nickname = '트슈';
UPDATE players SET soop_id = 'dkwkal', profile_image = '//profile.img.sooplive.co.kr/LOGO/dk/dkwkal/dkwkal.jpg' WHERE nickname = '탱크';
UPDATE players SET soop_id = 'kthrs9207', profile_image = '//profile.img.sooplive.co.kr/LOGO/kt/kthrs9207/kthrs9207.jpg' WHERE nickname = '파도';
UPDATE players SET soop_id = '70jeontaekyu', profile_image = '//profile.img.sooplive.co.kr/LOGO/70/70jeontaekyu/70jeontaekyu.jpg' WHERE nickname = '전태규';
UPDATE players SET soop_id = 'gmdtkak', profile_image = '//profile.img.sooplive.co.kr/LOGO/gm/gmdtkak/gmdtkak.jpg' WHERE nickname = '송현덕';
UPDATE players SET soop_id = 'wkddudrms15', profile_image = '//profile.img.sooplive.co.kr/LOGO/wk/wkddudrms15/wkddudrms15.jpg' WHERE nickname = '난수';
UPDATE players SET soop_id = 'luckycontrol', profile_image = '//profile.img.sooplive.co.kr/LOGO/lu/luckycontrol/luckycontrol.jpg' WHERE nickname = '고도준';
UPDATE players SET soop_id = 'dkswjddn92', profile_image = '//profile.img.sooplive.co.kr/LOGO/dk/dkswjddn92/dkswjddn92.jpg' WHERE nickname = '안정우';
UPDATE players SET soop_id = 'momjin', profile_image = '//profile.img.sooplive.co.kr/LOGO/mo/momjin/momjin.jpg' WHERE nickname = '서기수';
UPDATE players SET soop_id = 'erosrainbow', profile_image = '//profile.img.sooplive.co.kr/LOGO/er/erosrainbow/erosrainbow.jpg' WHERE nickname = '김성제';
UPDATE players SET soop_id = 'nalra82', profile_image = '//profile.img.sooplive.co.kr/LOGO/na/nalra82/nalra82.jpg' WHERE nickname = '강민';
UPDATE players SET soop_id = 'khm11903', profile_image = '//profile.img.sooplive.co.kr/LOGO/kh/khm11903/khm11903.jpg' WHERE nickname = '봉준';
UPDATE players SET soop_id = 'qksdy147', profile_image = '//profile.img.sooplive.co.kr/LOGO/qk/qksdy147/qksdy147.jpg' WHERE nickname = '하얀눈길';
UPDATE players SET soop_id = 'lovelove7777', profile_image = '//profile.img.sooplive.co.kr/LOGO/lo/lovelove7777/lovelove7777.jpg' WHERE nickname = '서지수';
UPDATE players SET soop_id = 'kuyol', profile_image = '//profile.img.sooplive.co.kr/LOGO/ku/kuyol/kuyol.jpg' WHERE nickname = '강구열';
UPDATE players SET soop_id = 'jipsh2', profile_image = '//profile.img.sooplive.co.kr/LOGO/ji/jipsh2/jipsh2.jpg' WHERE nickname = '내가스틱';
UPDATE players SET soop_id = 'ever316', profile_image = '//profile.img.sooplive.co.kr/LOGO/ev/ever316/ever316.jpg' WHERE nickname = '정소윤';
UPDATE players SET soop_id = 'kcl903', profile_image = '//profile.img.sooplive.co.kr/LOGO/kc/kcl903/kcl903.jpg' WHERE nickname = '채린쟝';
UPDATE players SET soop_id = 'zcv0320', profile_image = '//profile.img.sooplive.co.kr/LOGO/zc/zcv0320/zcv0320.jpg' WHERE nickname = '보혜';
UPDATE players SET soop_id = 'rlawhdwns6', profile_image = '//profile.img.sooplive.co.kr/LOGO/rl/rlawhdwns6/rlawhdwns6.jpg' WHERE nickname = '멍이에요';
UPDATE players SET soop_id = 'goodgame07', profile_image = '//profile.img.sooplive.co.kr/LOGO/go/goodgame07/goodgame07.jpg' WHERE nickname = '유성민';
UPDATE players SET soop_id = 'gjgj3274', profile_image = '//profile.img.sooplive.co.kr/LOGO/gj/gjgj3274/gjgj3274.jpg' WHERE nickname = '소룡이';
UPDATE players SET soop_id = 'kalmian', profile_image = '//profile.img.sooplive.co.kr/LOGO/ka/kalmian/kalmian.jpg' WHERE nickname = '토스봇';
UPDATE players SET soop_id = 'heksd', profile_image = '//profile.img.sooplive.co.kr/LOGO/he/heksd/heksd.jpg' WHERE nickname = '파메';
UPDATE players SET soop_id = 'jhpark7712', profile_image = '//profile.img.sooplive.co.kr/LOGO/jh/jhpark7712/jhpark7712.jpg' WHERE nickname = '빡재';
UPDATE players SET soop_id = 'chs9011', profile_image = '//profile.img.sooplive.co.kr/LOGO/ch/chs9011/chs9011.jpg' WHERE nickname = '모토케이';
UPDATE players SET soop_id = 'khc2566', profile_image = '//profile.img.sooplive.co.kr/LOGO/kh/khc2566/khc2566.jpg' WHERE nickname = '라히';
UPDATE players SET soop_id = 'dohyun83', profile_image = '//profile.img.sooplive.co.kr/LOGO/do/dohyun83/dohyun83.jpg' WHERE nickname = '나도현';
UPDATE players SET soop_id = 'bijyu90', profile_image = '//profile.img.sooplive.co.kr/LOGO/bi/bijyu90/bijyu90.jpg' WHERE nickname = '다린';
UPDATE players SET soop_id = 'igoldtree', profile_image = '//profile.img.sooplive.co.kr/LOGO/ig/igoldtree/igoldtree.jpg' WHERE nickname = '카리스';
UPDATE players SET soop_id = 'dudwn4974', profile_image = '//profile.img.sooplive.co.kr/LOGO/du/dudwn4974/dudwn4974.jpg' WHERE nickname = '안아';
UPDATE players SET soop_id = 'byebye22', profile_image = '//profile.img.sooplive.co.kr/LOGO/by/byebye22/byebye22.jpg' WHERE nickname = '애공';
UPDATE players SET soop_id = 'by0529', profile_image = '//profile.img.sooplive.co.kr/LOGO/by/by0529/by0529.jpg' WHERE nickname = '수입뿌드';
UPDATE players SET soop_id = 'measin', profile_image = '//profile.img.sooplive.co.kr/LOGO/me/measin/measin.jpg' WHERE nickname = '앙상국';
UPDATE players SET soop_id = 'killgusdnk', profile_image = '//profile.img.sooplive.co.kr/LOGO/ki/killgusdnk/killgusdnk.jpg' WHERE nickname = '클템';
UPDATE players SET soop_id = 'joey1114', profile_image = '//profile.img.sooplive.co.kr/LOGO/jo/joey1114/joey1114.jpg' WHERE nickname = '저라뎃';
UPDATE players SET soop_id = 'ehgmldud1233', profile_image = '//profile.img.sooplive.co.kr/LOGO/eh/ehgmldud1233/ehgmldud1233.jpg' WHERE nickname = '히엉';
UPDATE players SET soop_id = 'kwh1992', profile_image = '//profile.img.sooplive.co.kr/LOGO/kw/kwh1992/kwh1992.jpg' WHERE nickname = '우힝이';
UPDATE players SET soop_id = 'llqqqq', profile_image = '//profile.img.sooplive.co.kr/LOGO/ll/llqqqq/llqqqq.jpg' WHERE nickname = '혜로로';
UPDATE players SET soop_id = 'simcheong23', profile_image = '//profile.img.sooplive.co.kr/LOGO/si/simcheong23/simcheong23.jpg' WHERE nickname = '또봉순';
UPDATE players SET soop_id = 'rnaqpdrjf', profile_image = '//profile.img.sooplive.co.kr/LOGO/rn/rnaqpdrjf/rnaqpdrjf.jpg' WHERE nickname = '남덕선';
UPDATE players SET soop_id = 'yjk011599', profile_image = '//profile.img.sooplive.co.kr/LOGO/yj/yjk011599/yjk011599.jpg' WHERE nickname = '나무늘봉순';
UPDATE players SET soop_id = 'gddms97', profile_image = '//profile.img.sooplive.co.kr/LOGO/gd/gddms97/gddms97.jpg' WHERE nickname = '하블리';
UPDATE players SET soop_id = 'ghkdud1617', profile_image = '//profile.img.sooplive.co.kr/LOGO/gh/ghkdud1617/ghkdud1617.jpg' WHERE nickname = '카히리';
UPDATE players SET soop_id = 'seul0316', profile_image = '//profile.img.sooplive.co.kr/LOGO/se/seul0316/seul0316.jpg' WHERE nickname = '슬돌이';
UPDATE players SET soop_id = 'cyj982002', profile_image = '//profile.img.sooplive.co.kr/LOGO/cy/cyj982002/cyj982002.jpg' WHERE nickname = '다나짱';
UPDATE players SET soop_id = 'cat123123', profile_image = '//profile.img.sooplive.co.kr/LOGO/ca/cat123123/cat123123.jpg' WHERE nickname = '오리3';
UPDATE players SET soop_id = 'vlfvlf789', profile_image = '//profile.img.sooplive.co.kr/LOGO/vl/vlfvlf789/vlfvlf789.jpg' WHERE nickname = '빵훈';
UPDATE players SET soop_id = 'eeceec', profile_image = '//profile.img.sooplive.co.kr/LOGO/ee/eeceec/eeceec.jpg' WHERE nickname = '뚜미';
UPDATE players SET soop_id = 'phh95426', profile_image = '//profile.img.sooplive.co.kr/LOGO/ph/phh95426/phh95426.jpg' WHERE nickname = '소심';
UPDATE players SET soop_id = 'pookygamja', profile_image = '//profile.img.sooplive.co.kr/LOGO/po/pookygamja/pookygamja.jpg' WHERE nickname = '김인호';
UPDATE players SET soop_id = 'jjyjeh5454', profile_image = '//profile.img.sooplive.co.kr/LOGO/jj/jjyjeh5454/jjyjeh5454.jpg' WHERE nickname = '하리';
UPDATE players SET soop_id = 'ovoa3316', profile_image = '//profile.img.sooplive.co.kr/LOGO/ov/ovoa3316/ovoa3316.jpg' WHERE nickname = '나예리';
UPDATE players SET soop_id = 'bagguul', profile_image = '//profile.img.sooplive.co.kr/LOGO/ba/bagguul/bagguul.jpg' WHERE nickname = '규리야';
UPDATE players SET soop_id = 'wjswlgns09', profile_image = '//profile.img.sooplive.co.kr/LOGO/wj/wjswlgns09/wjswlgns09.jpg' WHERE nickname = '지두두';
UPDATE players SET soop_id = 'dksldi1010', profile_image = '//profile.img.sooplive.co.kr/LOGO/dk/dksldi1010/dksldi1010.jpg' WHERE nickname = '추르미';
UPDATE players SET soop_id = 'dkfka8945', profile_image = '//profile.img.sooplive.co.kr/LOGO/dk/dkfka8945/dkfka8945.jpg' WHERE nickname = '라미';
UPDATE players SET soop_id = 'jieun3297', profile_image = '//profile.img.sooplive.co.kr/LOGO/ji/jieun3297/jieun3297.jpg' WHERE nickname = '다예';
UPDATE players SET soop_id = 'pazzy1', profile_image = '//profile.img.sooplive.co.kr/LOGO/pa/pazzy1/pazzy1.jpg' WHERE nickname = '파찌';
UPDATE players SET soop_id = '595935', profile_image = '//profile.img.sooplive.co.kr/LOGO/59/595935/595935.jpg' WHERE nickname = '상어녀';
UPDATE players SET soop_id = 'dmswls4565', profile_image = '//profile.img.sooplive.co.kr/LOGO/dm/dmswls4565/dmswls4565.jpg' WHERE nickname = '공다츠';
UPDATE players SET soop_id = 'boyun96', profile_image = '//profile.img.sooplive.co.kr/LOGO/bo/boyun96/boyun96.jpg' WHERE nickname = '김뽀뇨';
UPDATE players SET soop_id = 'rlsk0705', profile_image = '//profile.img.sooplive.co.kr/LOGO/rl/rlsk0705/rlsk0705.jpg' WHERE nickname = '기나';
UPDATE players SET soop_id = 'bora99', profile_image = '//profile.img.sooplive.co.kr/LOGO/bo/bora99/bora99.jpg' WHERE nickname = '구보라';
UPDATE players SET soop_id = 'xvvx1859', profile_image = '//profile.img.sooplive.co.kr/LOGO/xv/xvvx1859/xvvx1859.jpg' WHERE nickname = '별비';
UPDATE players SET soop_id = 'forweourus', profile_image = '//profile.img.sooplive.co.kr/LOGO/fo/forweourus/forweourus.jpg' WHERE nickname = '이유란';
UPDATE players SET soop_id = 'parkle1006', profile_image = '//profile.img.sooplive.co.kr/LOGO/pa/parkle1006/parkle1006.jpg' WHERE nickname = '박듀듀';
UPDATE players SET soop_id = 'freshtomato', profile_image = '//profile.img.sooplive.co.kr/LOGO/fr/freshtomato/freshtomato.jpg' WHERE nickname = '토마토';
UPDATE players SET soop_id = 'yoomingseo', profile_image = '//profile.img.sooplive.co.kr/LOGO/yo/yoomingseo/yoomingseo.jpg' WHERE nickname = '유복실';
UPDATE players SET soop_id = 'soonhani', profile_image = '//profile.img.sooplive.co.kr/LOGO/so/soonhani/soonhani.jpg' WHERE nickname = '최하니';
UPDATE players SET soop_id = 'jscando77', profile_image = '//profile.img.sooplive.co.kr/LOGO/js/jscando77/jscando77.jpg' WHERE nickname = '빵리나';
UPDATE players SET soop_id = 'superbsw123', profile_image = '//profile.img.sooplive.co.kr/LOGO/su/superbsw123/superbsw123.jpg' WHERE nickname = '시조새';
UPDATE players SET soop_id = 'xodud1898', profile_image = '//profile.img.sooplive.co.kr/LOGO/xo/xodud1898/xodud1898.jpg' WHERE nickname = '태영';
UPDATE players SET soop_id = 'kwbm123081', profile_image = '//profile.img.sooplive.co.kr/LOGO/kw/kwbm123081/kwbm123081.jpg' WHERE nickname = '금선2';
UPDATE players SET soop_id = 'thelddl', profile_image = '//profile.img.sooplive.co.kr/LOGO/th/thelddl/thelddl.jpg' WHERE nickname = '햇살';
UPDATE players SET soop_id = 'kmj05317', profile_image = '//profile.img.sooplive.co.kr/LOGO/km/kmj05317/kmj05317.jpg' WHERE nickname = '우리밍';
UPDATE players SET soop_id = 'zalalz', profile_image = '//profile.img.sooplive.co.kr/LOGO/za/zalalz/zalalz.jpg' WHERE nickname = '오조은';
UPDATE players SET soop_id = 'haru1207', profile_image = '//profile.img.sooplive.co.kr/LOGO/ha/haru1207/haru1207.jpg' WHERE nickname = '쥬나';
UPDATE players SET soop_id = 'yeeeahm97', profile_image = '//profile.img.sooplive.co.kr/LOGO/ye/yeeeahm97/yeeeahm97.jpg' WHERE nickname = '림예이';
UPDATE players SET soop_id = 'clclcl8888', profile_image = '//profile.img.sooplive.co.kr/LOGO/cl/clclcl8888/clclcl8888.jpg' WHERE nickname = '늑대채린';
UPDATE players SET soop_id = 'tjgpdus97', profile_image = '//profile.img.sooplive.co.kr/LOGO/tj/tjgpdus97/tjgpdus97.jpg' WHERE nickname = '요닝';
UPDATE players SET soop_id = 'alaelddl97', profile_image = '//profile.img.sooplive.co.kr/LOGO/al/alaelddl97/alaelddl97.jpg' WHERE nickname = '찌킹';
UPDATE players SET soop_id = 'totlllsz', profile_image = '//profile.img.sooplive.co.kr/LOGO/to/totlllsz/totlllsz.jpg' WHERE nickname = '몽순';
UPDATE players SET soop_id = 'lily0104', profile_image = '//profile.img.sooplive.co.kr/LOGO/li/lily0104/lily0104.jpg' WHERE nickname = '정소이';
UPDATE players SET soop_id = '9rumee', profile_image = '//profile.img.sooplive.co.kr/LOGO/9r/9rumee/9rumee.jpg' WHERE nickname = '구루미';
UPDATE players SET soop_id = 'ekfrqkf', profile_image = '//profile.img.sooplive.co.kr/LOGO/ek/ekfrqkf/ekfrqkf.jpg' WHERE nickname = '슬아';
UPDATE players SET soop_id = 'agah1106', profile_image = '//profile.img.sooplive.co.kr/LOGO/ag/agah1106/agah1106.jpg' WHERE nickname = '링고';
UPDATE players SET soop_id = 'ftrudals', profile_image = '//profile.img.sooplive.co.kr/LOGO/ft/ftrudals/ftrudals.jpg' WHERE nickname = '나린';
UPDATE players SET soop_id = 'dbwjdcool1', profile_image = '//profile.img.sooplive.co.kr/LOGO/db/dbwjdcool1/dbwjdcool1.jpg' WHERE nickname = '키링';
UPDATE players SET soop_id = 'dlaalswl22', profile_image = '//profile.img.sooplive.co.kr/LOGO/dl/dlaalswl22/dlaalswl22.jpg' WHERE nickname = '임밍지';
UPDATE players SET soop_id = 'yochba0402', profile_image = '//profile.img.sooplive.co.kr/LOGO/yo/yochba0402/yochba0402.jpg' WHERE nickname = '졈니';
UPDATE players SET soop_id = '123rhaxld', profile_image = '//profile.img.sooplive.co.kr/LOGO/12/123rhaxld/123rhaxld.jpg' WHERE nickname = '최도랑';
UPDATE players SET soop_id = 'djathekd', profile_image = '//profile.img.sooplive.co.kr/LOGO/dj/djathekd/djathekd.jpg' WHERE nickname = '연애인';
UPDATE players SET soop_id = 'kitty1029', profile_image = '//profile.img.sooplive.co.kr/LOGO/ki/kitty1029/kitty1029.jpg' WHERE nickname = '꼬니부깅';
UPDATE players SET soop_id = 'ddd001', profile_image = '//profile.img.sooplive.co.kr/LOGO/dd/ddd001/ddd001.jpg' WHERE nickname = '은똥';
UPDATE players SET soop_id = 'nerve89', profile_image = '//profile.img.sooplive.co.kr/LOGO/ne/nerve89/nerve89.jpg' WHERE nickname = '깨림이';
UPDATE players SET soop_id = 'kangjikk', profile_image = '//profile.img.sooplive.co.kr/LOGO/ka/kangjikk/kangjikk.jpg' WHERE nickname = '만다';
UPDATE players SET soop_id = 'bjcherrybs', profile_image = '//profile.img.sooplive.co.kr/LOGO/bj/bjcherrybs/bjcherrybs.jpg' WHERE nickname = '김하선';
UPDATE players SET soop_id = 'hy4985', profile_image = '//profile.img.sooplive.co.kr/LOGO/hy/hy4985/hy4985.jpg' WHERE nickname = '뽀누나';
UPDATE players SET soop_id = 'synyoung', profile_image = '//profile.img.sooplive.co.kr/LOGO/sy/synyoung/synyoung.jpg' WHERE nickname = '시녕뭉';
UPDATE players SET soop_id = 'sdkels', profile_image = '//profile.img.sooplive.co.kr/LOGO/sd/sdkels/sdkels.jpg' WHERE nickname = '강덕구';
UPDATE players SET soop_id = 'soju2022', profile_image = '//profile.img.sooplive.co.kr/LOGO/so/soju2022/soju2022.jpg' WHERE nickname = '소주양';
UPDATE players SET soop_id = 'chchchshai', profile_image = '//profile.img.sooplive.co.kr/LOGO/ch/chchchshai/chchchshai.jpg' WHERE nickname = '유이';
UPDATE players SET soop_id = 'db001202', profile_image = '//profile.img.sooplive.co.kr/LOGO/db/db001202/db001202.jpg' WHERE nickname = '치리';
UPDATE players SET soop_id = 'ldk8481', profile_image = '//profile.img.sooplive.co.kr/LOGO/ld/ldk8481/ldk8481.jpg' WHERE nickname = '슈슈';
UPDATE players SET soop_id = 'rhf104', profile_image = '//profile.img.sooplive.co.kr/LOGO/rh/rhf104/rhf104.jpg' WHERE nickname = '란란';
UPDATE players SET soop_id = 'nylove276', profile_image = '//profile.img.sooplive.co.kr/LOGO/ny/nylove276/nylove276.jpg' WHERE nickname = '삐약삐약';
UPDATE players SET soop_id = 'xshinx', profile_image = '//profile.img.sooplive.co.kr/LOGO/xs/xshinx/xshinx.jpg' WHERE nickname = '단양';
UPDATE players SET soop_id = 'aram1213', profile_image = '//profile.img.sooplive.co.kr/LOGO/ar/aram1213/aram1213.jpg' WHERE nickname = '아라미';
UPDATE players SET soop_id = 'della2440', profile_image = '//profile.img.sooplive.co.kr/LOGO/de/della2440/della2440.jpg' WHERE nickname = '예실';
UPDATE players SET soop_id = 'fpahsdltu1', profile_image = '//profile.img.sooplive.co.kr/LOGO/fp/fpahsdltu1/fpahsdltu1.jpg' WHERE nickname = '주하랑';
UPDATE players SET soop_id = 'gkdud3294', profile_image = '//profile.img.sooplive.co.kr/LOGO/gk/gkdud3294/gkdud3294.jpg' WHERE nickname = '오하얀';
UPDATE players SET soop_id = 'snowssa', profile_image = '//profile.img.sooplive.co.kr/LOGO/sn/snowssa/snowssa.jpg' WHERE nickname = '설둥이';
UPDATE players SET soop_id = 'dptmfl1258', profile_image = '//profile.img.sooplive.co.kr/LOGO/dp/dptmfl1258/dptmfl1258.jpg' WHERE nickname = '예슬';
UPDATE players SET soop_id = 'dmsthfdldia', profile_image = '//profile.img.sooplive.co.kr/LOGO/dm/dmsthfdldia/dmsthfdldia.jpg' WHERE nickname = '라운이';
UPDATE players SET soop_id = 'ka9rapang', profile_image = '//profile.img.sooplive.co.kr/LOGO/ka/ka9rapang/ka9rapang.jpg' WHERE nickname = '연둥바둥';
UPDATE players SET soop_id = 'ititit', profile_image = '//profile.img.sooplive.co.kr/LOGO/it/ititit/ititit.jpg' WHERE nickname = '정중만';
UPDATE players SET soop_id = 'rabbitmiffy', profile_image = '//profile.img.sooplive.co.kr/LOGO/ra/rabbitmiffy/rabbitmiffy.jpg' WHERE nickname = '최세상';
UPDATE players SET soop_id = 'ys9024', profile_image = '//profile.img.sooplive.co.kr/LOGO/ys/ys9024/ys9024.jpg' WHERE nickname = '주서리';
UPDATE players SET soop_id = 'nodubu', profile_image = '//profile.img.sooplive.co.kr/LOGO/no/nodubu/nodubu.jpg' WHERE nickname = '묘아';
UPDATE players SET soop_id = 'seemin88', profile_image = '//profile.img.sooplive.co.kr/LOGO/se/seemin88/seemin88.jpg' WHERE nickname = '비타밍';
UPDATE players SET soop_id = 'moguleave', profile_image = '//profile.img.sooplive.co.kr/LOGO/mo/moguleave/moguleave.jpg' WHERE nickname = '모리';
UPDATE players SET soop_id = 'rhakdncjs90', profile_image = '//profile.img.sooplive.co.kr/LOGO/rh/rhakdncjs90/rhakdncjs90.jpg' WHERE nickname = '으냉이';
UPDATE players SET soop_id = 'tjwjddms1565', profile_image = '//profile.img.sooplive.co.kr/LOGO/tj/tjwjddms1565/tjwjddms1565.jpg' WHERE nickname = '선정은';
UPDATE players SET soop_id = 'yunheehoho', profile_image = '//profile.img.sooplive.co.kr/LOGO/yu/yunheehoho/yunheehoho.jpg' WHERE nickname = '서윤';
UPDATE players SET soop_id = 'meyou0107', profile_image = '//profile.img.sooplive.co.kr/LOGO/me/meyou0107/meyou0107.jpg' WHERE nickname = '빵미유';
UPDATE players SET soop_id = 'fudnjs0235', profile_image = '//profile.img.sooplive.co.kr/LOGO/fu/fudnjs0235/fudnjs0235.jpg' WHERE nickname = '려원';
UPDATE players SET soop_id = 'maeong2', profile_image = '//profile.img.sooplive.co.kr/LOGO/ma/maeong2/maeong2.jpg' WHERE nickname = '메옹';
UPDATE players SET soop_id = 'nasd06', profile_image = '//profile.img.sooplive.co.kr/LOGO/na/nasd06/nasd06.jpg' WHERE nickname = '수니양';
UPDATE players SET soop_id = 'goni2677', profile_image = '//profile.img.sooplive.co.kr/LOGO/go/goni2677/goni2677.jpg' WHERE nickname = '내가먼지';
UPDATE players SET soop_id = '2ahgo1203', profile_image = '//profile.img.sooplive.co.kr/LOGO/2a/2ahgo1203/2ahgo1203.jpg' WHERE nickname = '이아깽';
UPDATE players SET soop_id = 'lingolinga', profile_image = '//profile.img.sooplive.co.kr/LOGO/li/lingolinga/lingolinga.jpg' WHERE nickname = '링가';
UPDATE players SET soop_id = 'lkim12', profile_image = '//profile.img.sooplive.co.kr/LOGO/lk/lkim12/lkim12.jpg' WHERE nickname = '뚜비';
UPDATE players SET soop_id = 'pokimasiso', profile_image = '//profile.img.sooplive.co.kr/LOGO/po/pokimasiso/pokimasiso.jpg' WHERE nickname = '또해영';
UPDATE players SET soop_id = 'wlgua7272', profile_image = '//profile.img.sooplive.co.kr/LOGO/wl/wlgua7272/wlgua7272.jpg' WHERE nickname = '2라니';
UPDATE players SET soop_id = 'khsoo0105', profile_image = '//profile.img.sooplive.co.kr/LOGO/kh/khsoo0105/khsoo0105.jpg' WHERE nickname = '귀요민정';
UPDATE players SET soop_id = 'chziaxz', profile_image = '//profile.img.sooplive.co.kr/LOGO/ch/chziaxz/chziaxz.jpg' WHERE nickname = '도릿';
UPDATE players SET soop_id = 'nk0990409', profile_image = '//profile.img.sooplive.co.kr/LOGO/nk/nk0990409/nk0990409.jpg' WHERE nickname = '김태향';
UPDATE players SET soop_id = 'qkrgkdms01', profile_image = '//profile.img.sooplive.co.kr/LOGO/qk/qkrgkdms01/qkrgkdms01.jpg' WHERE nickname = '박하악';
UPDATE players SET soop_id = 'alsgus00', profile_image = '//profile.img.sooplive.co.kr/LOGO/al/alsgus00/alsgus00.jpg' WHERE nickname = '미니언';
UPDATE players SET soop_id = 'imducko3o', profile_image = '//profile.img.sooplive.co.kr/LOGO/im/imducko3o/imducko3o.jpg' WHERE nickname = '오리꿍';
UPDATE players SET soop_id = 'dlrnf', profile_image = '//profile.img.sooplive.co.kr/LOGO/dl/dlrnf/dlrnf.jpg' WHERE nickname = '쌍디';
UPDATE players SET soop_id = 'dlaguswl501', profile_image = '//profile.img.sooplive.co.kr/LOGO/dl/dlaguswl501/dlaguswl501.jpg' WHERE nickname = '임조이';
UPDATE players SET soop_id = 'rnfma14', profile_image = '//profile.img.sooplive.co.kr/LOGO/rn/rnfma14/rnfma14.jpg' WHERE nickname = '김설';
UPDATE players SET soop_id = 'ynblbee', profile_image = '//profile.img.sooplive.co.kr/LOGO/yn/ynblbee/ynblbee.jpg' WHERE nickname = '연블비';
UPDATE players SET soop_id = 'have1y', profile_image = '//profile.img.sooplive.co.kr/LOGO/ha/have1y/have1y.jpg' WHERE nickname = '김채이';
UPDATE players SET soop_id = 'jmk5883', profile_image = '//profile.img.sooplive.co.kr/LOGO/jm/jmk5883/jmk5883.jpg' WHERE nickname = '양유정';
UPDATE players SET soop_id = 'daum0319', profile_image = '//profile.img.sooplive.co.kr/LOGO/da/daum0319/daum0319.jpg' WHERE nickname = '다우미';
UPDATE players SET soop_id = 'tato1104', profile_image = '//profile.img.sooplive.co.kr/LOGO/ta/tato1104/tato1104.jpg' WHERE nickname = '밍가';
UPDATE players SET soop_id = 'jjjjeong', profile_image = '//profile.img.sooplive.co.kr/LOGO/jj/jjjjeong/jjjjeong.jpg' WHERE nickname = '태린';
UPDATE players SET soop_id = 'mooaoom', profile_image = '//profile.img.sooplive.co.kr/LOGO/mo/mooaoom/mooaoom.jpg' WHERE nickname = '김무아';
UPDATE players SET soop_id = 'aaaa7979', profile_image = '//profile.img.sooplive.co.kr/LOGO/aa/aaaa7979/aaaa7979.jpg' WHERE nickname = '뿌하';
UPDATE players SET soop_id = 'qocnrhdwn1', profile_image = '//profile.img.sooplive.co.kr/LOGO/qo/qocnrhdwn1/qocnrhdwn1.jpg' WHERE nickname = '연수';
UPDATE players SET soop_id = 'hee4343', profile_image = '//profile.img.sooplive.co.kr/LOGO/he/hee4343/hee4343.jpg' WHERE nickname = '비재희';
UPDATE players SET soop_id = 'wlsdkd1', profile_image = '//profile.img.sooplive.co.kr/LOGO/wl/wlsdkd1/wlsdkd1.jpg' WHERE nickname = '엄보리';
UPDATE players SET soop_id = 'aybjc2319', profile_image = '//profile.img.sooplive.co.kr/LOGO/ay/aybjc2319/aybjc2319.jpg' WHERE nickname = '진유성';
UPDATE players SET soop_id = 'mew030709', profile_image = '//profile.img.sooplive.co.kr/LOGO/me/mew030709/mew030709.jpg' WHERE nickname = '남수댕';
UPDATE players SET soop_id = 'zzzz809', profile_image = '//profile.img.sooplive.co.kr/LOGO/zz/zzzz809/zzzz809.jpg' WHERE nickname = '백갑숙';
UPDATE players SET soop_id = 'candyrang00', profile_image = '//profile.img.sooplive.co.kr/LOGO/ca/candyrang00/candyrang00.jpg' WHERE nickname = '하랑e';
UPDATE players SET soop_id = 'popoten', profile_image = '//profile.img.sooplive.co.kr/LOGO/po/popoten/popoten.jpg' WHERE nickname = '팥순';
UPDATE players SET soop_id = 'busky3', profile_image = '//profile.img.sooplive.co.kr/LOGO/bu/busky3/busky3.jpg' WHERE nickname = '하두링';
UPDATE players SET soop_id = 'dyaan0v0', profile_image = '//profile.img.sooplive.co.kr/LOGO/dy/dyaan0v0/dyaan0v0.jpg' WHERE nickname = '정다닝';
UPDATE players SET soop_id = 'jiinii000', profile_image = '//profile.img.sooplive.co.kr/LOGO/ji/jiinii000/jiinii000.jpg' WHERE nickname = '밥새';
UPDATE players SET soop_id = 'asdsa1113', profile_image = '//profile.img.sooplive.co.kr/LOGO/as/asdsa1113/asdsa1113.jpg' WHERE nickname = '세월';
UPDATE players SET soop_id = 'son4069', profile_image = '//profile.img.sooplive.co.kr/LOGO/so/son4069/son4069.jpg' WHERE nickname = '빵지니';
UPDATE players SET soop_id = 'rudzhd123', profile_image = '//profile.img.sooplive.co.kr/LOGO/ru/rudzhd123/rudzhd123.jpg' WHERE nickname = '경콩';
UPDATE players SET soop_id = '5eulgii', profile_image = '//profile.img.sooplive.co.kr/LOGO/5e/5eulgii/5eulgii.jpg' WHERE nickname = '김말랑';
UPDATE players SET soop_id = 'min030606', profile_image = '//profile.img.sooplive.co.kr/LOGO/mi/min030606/min030606.jpg' WHERE nickname = '면추가';
UPDATE players SET soop_id = 'wittyku', profile_image = '//profile.img.sooplive.co.kr/LOGO/wi/wittyku/wittyku.jpg' WHERE nickname = '냥수디';
UPDATE players SET soop_id = 'wjddmstj79', profile_image = '//profile.img.sooplive.co.kr/LOGO/wj/wjddmstj79/wjddmstj79.jpg' WHERE nickname = '쟈닌';
UPDATE players SET soop_id = '2meonjin', profile_image = '//profile.img.sooplive.co.kr/LOGO/2m/2meonjin/2meonjin.jpg' WHERE nickname = '먼진';
UPDATE players SET soop_id = 'kittysh1', profile_image = '//profile.img.sooplive.co.kr/LOGO/ki/kittysh1/kittysh1.jpg' WHERE nickname = '키모야';
UPDATE players SET soop_id = 'nreupne', profile_image = '//profile.img.sooplive.co.kr/LOGO/nr/nreupne/nreupne.jpg' WHERE nickname = '핑핑';
UPDATE players SET soop_id = 'youaregood', profile_image = '//profile.img.sooplive.co.kr/LOGO/yo/youaregood/youaregood.jpg' WHERE nickname = '진니';
UPDATE players SET soop_id = 'toy2053', profile_image = '//profile.img.sooplive.co.kr/LOGO/to/toy2053/toy2053.jpg' WHERE nickname = '햄찌야';
UPDATE players SET soop_id = 'harumyong', profile_image = '//profile.img.sooplive.co.kr/LOGO/ha/harumyong/harumyong.jpg' WHERE nickname = '하루묭';
UPDATE players SET soop_id = 'danu619', profile_image = '//profile.img.sooplive.co.kr/LOGO/da/danu619/danu619.jpg' WHERE nickname = '다뉴';
UPDATE players SET soop_id = 'queenzu', profile_image = '//profile.img.sooplive.co.kr/LOGO/qu/queenzu/queenzu.jpg' WHERE nickname = '퀸주';
UPDATE players SET soop_id = 'seols2', profile_image = '//profile.img.sooplive.co.kr/LOGO/se/seols2/seols2.jpg' WHERE nickname = '정서린';
UPDATE players SET soop_id = 'diniowo', profile_image = '//profile.img.sooplive.co.kr/LOGO/di/diniowo/diniowo.jpg' WHERE nickname = '막내현진';
UPDATE players SET soop_id = 'queen030', profile_image = '//profile.img.sooplive.co.kr/LOGO/qu/queen030/queen030.jpg' WHERE nickname = '효짱';
UPDATE players SET soop_id = 'nyayoung98', profile_image = '//profile.img.sooplive.co.kr/LOGO/ny/nyayoung98/nyayoung98.jpg' WHERE nickname = '우마루대장';
UPDATE players SET soop_id = 'e9dongsung', profile_image = '//profile.img.sooplive.co.kr/LOGO/e9/e9dongsung/e9dongsung.jpg' WHERE nickname = '이주헌';
UPDATE players SET soop_id = 'eunseo0152', profile_image = '//profile.img.sooplive.co.kr/LOGO/eu/eunseo0152/eunseo0152.jpg' WHERE nickname = '은서';
UPDATE players SET soop_id = 'zzonii', profile_image = '//profile.img.sooplive.co.kr/LOGO/zz/zzonii/zzonii.jpg' WHERE nickname = '한쪼니';
UPDATE players SET soop_id = 'yyssaa33', profile_image = '//profile.img.sooplive.co.kr/LOGO/yy/yyssaa33/yyssaa33.jpg' WHERE nickname = '제티';
UPDATE players SET soop_id = 's2appeal', profile_image = '//profile.img.sooplive.co.kr/LOGO/s2/s2appeal/s2appeal.jpg' WHERE nickname = '흑설';
UPDATE players SET soop_id = 'vldpfm2', profile_image = '//profile.img.sooplive.co.kr/LOGO/vl/vldpfm2/vldpfm2.jpg' WHERE nickname = '아리송이';
UPDATE players SET soop_id = 'wony218', profile_image = '//profile.img.sooplive.co.kr/LOGO/wo/wony218/wony218.jpg' WHERE nickname = '욱하는형';
UPDATE players SET soop_id = 'daejoong007', profile_image = '//profile.img.sooplive.co.kr/LOGO/da/daejoong007/daejoong007.jpg' WHERE nickname = '이기광';
UPDATE players SET soop_id = 'dollooo', profile_image = '//profile.img.sooplive.co.kr/LOGO/do/dollooo/dollooo.jpg' WHERE nickname = '제갈츄빈';
UPDATE players SET soop_id = 'gangeda', profile_image = '//profile.img.sooplive.co.kr/LOGO/ga/gangeda/gangeda.jpg' WHERE nickname = '갱이다';
UPDATE players SET soop_id = 'chanmeyo', profile_image = '//profile.img.sooplive.co.kr/LOGO/ch/chanmeyo/chanmeyo.jpg' WHERE nickname = '김세주';
UPDATE players SET soop_id = 'thdeksql', profile_image = '//profile.img.sooplive.co.kr/LOGO/th/thdeksql/thdeksql.jpg' WHERE nickname = '단비송';
UPDATE players SET soop_id = 'finepearls', profile_image = '//profile.img.sooplive.co.kr/LOGO/fi/finepearls/finepearls.jpg' WHERE nickname = '혜냥';
UPDATE players SET soop_id = 'jiwooris2', profile_image = '//profile.img.sooplive.co.kr/LOGO/ji/jiwooris2/jiwooris2.jpg' WHERE nickname = '지우리';
UPDATE players SET soop_id = 'segguswjd', profile_image = '//profile.img.sooplive.co.kr/LOGO/se/segguswjd/segguswjd.jpg' WHERE nickname = '돌애정';
UPDATE players SET soop_id = 'totoo23', profile_image = '//profile.img.sooplive.co.kr/LOGO/to/totoo23/totoo23.jpg' WHERE nickname = '밍또얌';
UPDATE players SET soop_id = 'roa0216', profile_image = '//profile.img.sooplive.co.kr/LOGO/ro/roa0216/roa0216.jpg' WHERE nickname = '허로아';
UPDATE players SET soop_id = 'rememberdk', profile_image = '//profile.img.sooplive.co.kr/LOGO/re/rememberdk/rememberdk.jpg' WHERE nickname = '여운';
UPDATE players SET soop_id = 'dlwldyal1004', profile_image = '//profile.img.sooplive.co.kr/LOGO/dl/dlwldyal1004/dlwldyal1004.jpg' WHERE nickname = '이지다';
UPDATE players SET soop_id = 'begoniah', profile_image = '//profile.img.sooplive.co.kr/LOGO/be/begoniah/begoniah.jpg' WHERE nickname = '백원이야';
UPDATE players SET soop_id = 'corgi1102', profile_image = '//profile.img.sooplive.co.kr/LOGO/co/corgi1102/corgi1102.jpg' WHERE nickname = '냥냥코기';
UPDATE players SET soop_id = 'gmlwldi', profile_image = '//profile.img.sooplive.co.kr/LOGO/gm/gmlwldi/gmlwldi.jpg' WHERE nickname = '구쁘';
UPDATE players SET soop_id = 'hikikojjang', profile_image = '//profile.img.sooplive.co.kr/LOGO/hi/hikikojjang/hikikojjang.jpg' WHERE nickname = '행복짱';
UPDATE players SET soop_id = 'ghlidhjgioew', profile_image = '//profile.img.sooplive.co.kr/LOGO/gh/ghlidhjgioew/ghlidhjgioew.jpg' WHERE nickname = '다라츄';
UPDATE players SET soop_id = 'xzqwe1', profile_image = '//profile.img.sooplive.co.kr/LOGO/xz/xzqwe1/xzqwe1.jpg' WHERE nickname = '황단비';
UPDATE players SET soop_id = 'thfk13579', profile_image = '//profile.img.sooplive.co.kr/LOGO/th/thfk13579/thfk13579.jpg' WHERE nickname = '민트';
UPDATE players SET soop_id = 'jsg0301', profile_image = '//profile.img.sooplive.co.kr/LOGO/js/jsg0301/jsg0301.jpg' WHERE nickname = '삼교';
UPDATE players SET soop_id = 'n0219ekdms', profile_image = '//profile.img.sooplive.co.kr/LOGO/n0/n0219ekdms/n0219ekdms.jpg' WHERE nickname = '단이';
UPDATE players SET soop_id = 'kjy3443', profile_image = '//profile.img.sooplive.co.kr/LOGO/kj/kjy3443/kjy3443.jpg' WHERE nickname = '연또';
UPDATE players SET soop_id = 'eunjo0105', profile_image = '//profile.img.sooplive.co.kr/LOGO/eu/eunjo0105/eunjo0105.jpg' WHERE nickname = '은조';
UPDATE players SET soop_id = 'dlqudgk1227', profile_image = '//profile.img.sooplive.co.kr/LOGO/dl/dlqudgk1227/dlqudgk1227.jpg' WHERE nickname = '병하';
UPDATE players SET soop_id = 'roket0829', profile_image = '//profile.img.sooplive.co.kr/LOGO/ro/roket0829/roket0829.jpg' WHERE nickname = '박퍼니';
UPDATE players SET soop_id = 'toald4187', profile_image = '//profile.img.sooplive.co.kr/LOGO/to/toald4187/toald4187.jpg' WHERE nickname = '새밍';
UPDATE players SET soop_id = 'jeongus134', profile_image = '//profile.img.sooplive.co.kr/LOGO/je/jeongus134/jeongus134.jpg' WHERE nickname = '안나';
UPDATE players SET soop_id = 'eun0c0', profile_image = '//profile.img.sooplive.co.kr/LOGO/eu/eun0c0/eun0c0.jpg' WHERE nickname = '햇참새';
UPDATE players SET soop_id = 'wlswn6565', profile_image = '//profile.img.sooplive.co.kr/LOGO/wl/wlswn6565/wlswn6565.jpg' WHERE nickname = '진땅콩';
UPDATE players SET soop_id = 'jungym0116', profile_image = '//profile.img.sooplive.co.kr/LOGO/ju/jungym0116/jungym0116.jpg' WHERE nickname = '아링';
UPDATE players SET soop_id = 'sa03030', profile_image = '//profile.img.sooplive.co.kr/LOGO/sa/sa03030/sa03030.jpg' WHERE nickname = '다예나';
UPDATE players SET soop_id = 'umji1218', profile_image = '//profile.img.sooplive.co.kr/LOGO/um/umji1218/umji1218.jpg' WHERE nickname = '엄키키';
UPDATE players SET soop_id = 'khl1589', profile_image = '//profile.img.sooplive.co.kr/LOGO/kh/khl1589/khl1589.jpg' WHERE nickname = '요시';
UPDATE players SET soop_id = 'kimp1ay', profile_image = '//profile.img.sooplive.co.kr/LOGO/ki/kimp1ay/kimp1ay.jpg' WHERE nickname = '구키';
UPDATE players SET soop_id = 'hiyoko040', profile_image = '//profile.img.sooplive.co.kr/LOGO/hi/hiyoko040/hiyoko040.jpg' WHERE nickname = '히요코';
UPDATE players SET soop_id = 'eun9116', profile_image = '//profile.img.sooplive.co.kr/LOGO/eu/eun9116/eun9116.jpg' WHERE nickname = '비그리';
UPDATE players SET soop_id = 'jjooree', profile_image = '//profile.img.sooplive.co.kr/LOGO/jj/jjooree/jjooree.jpg' WHERE nickname = '이주리';
UPDATE players SET soop_id = 'yen1993', profile_image = '//profile.img.sooplive.co.kr/LOGO/ye/yen1993/yen1993.jpg' WHERE nickname = '하이유';
UPDATE players SET soop_id = 'nkelly6085', profile_image = '//profile.img.sooplive.co.kr/LOGO/nk/nkelly6085/nkelly6085.jpg' WHERE nickname = '지아송';
UPDATE players SET soop_id = 'heyyo0123', profile_image = '//profile.img.sooplive.co.kr/LOGO/he/heyyo0123/heyyo0123.jpg' WHERE nickname = '헤요이';
UPDATE players SET soop_id = 'kus03125', profile_image = '//profile.img.sooplive.co.kr/LOGO/ku/kus03125/kus03125.jpg' WHERE nickname = '뀨알';
UPDATE players SET soop_id = 'owoouoowo', profile_image = '//profile.img.sooplive.co.kr/LOGO/ow/owoouoowo/owoouoowo.jpg' WHERE nickname = '모비';
UPDATE players SET soop_id = 'cheto1206', profile_image = '//profile.img.sooplive.co.kr/LOGO/ch/cheto1206/cheto1206.jpg' WHERE nickname = '먹체토';
UPDATE players SET soop_id = 'qwerbb1', profile_image = '//profile.img.sooplive.co.kr/LOGO/qw/qwerbb1/qwerbb1.jpg' WHERE nickname = '예꾸';
UPDATE players SET soop_id = 'clzhf123', profile_image = '//profile.img.sooplive.co.kr/LOGO/cl/clzhf123/clzhf123.jpg' WHERE nickname = '우질';
UPDATE players SET soop_id = 'siahag', profile_image = '//profile.img.sooplive.co.kr/LOGO/si/siahag/siahag.jpg' WHERE nickname = '찡찡시아';
UPDATE players SET soop_id = 'yeom1020', profile_image = '//profile.img.sooplive.co.kr/LOGO/ye/yeom1020/yeom1020.jpg' WHERE nickname = '정연이';
UPDATE players SET soop_id = 'tiger3006', profile_image = '//profile.img.sooplive.co.kr/LOGO/ti/tiger3006/tiger3006.jpg' WHERE nickname = '마예준';
UPDATE players SET soop_id = 'tkdduddb06', profile_image = '//profile.img.sooplive.co.kr/LOGO/tk/tkdduddb06/tkdduddb06.jpg' WHERE nickname = '와이퍼';
UPDATE players SET soop_id = 'zpdl1313', profile_image = '//profile.img.sooplive.co.kr/LOGO/zp/zpdl1313/zpdl1313.jpg' WHERE nickname = '케이';
UPDATE players SET soop_id = 'haeun5513', profile_image = '//profile.img.sooplive.co.kr/LOGO/ha/haeun5513/haeun5513.jpg' WHERE nickname = '밤하밍';
UPDATE players SET soop_id = 'kjhanna824', profile_image = '//profile.img.sooplive.co.kr/LOGO/kj/kjhanna824/kjhanna824.jpg' WHERE nickname = '미진이';
UPDATE players SET soop_id = 'onzzang', profile_image = '//profile.img.sooplive.co.kr/LOGO/on/onzzang/onzzang.jpg' WHERE nickname = '이응씨';
UPDATE players SET soop_id = 'x1aohongmao', profile_image = '//profile.img.sooplive.co.kr/LOGO/x1/x1aohongmao/x1aohongmao.jpg' WHERE nickname = '오세은';
UPDATE players SET soop_id = 'yuzzzz', profile_image = '//profile.img.sooplive.co.kr/LOGO/yu/yuzzzz/yuzzzz.jpg' WHERE nickname = '유즈';
UPDATE players SET soop_id = 'mkyung0331', profile_image = '//profile.img.sooplive.co.kr/LOGO/mk/mkyung0331/mkyung0331.jpg' WHERE nickname = '초이';
UPDATE players SET soop_id = 'goyo030', profile_image = '//profile.img.sooplive.co.kr/LOGO/go/goyo030/goyo030.jpg' WHERE nickname = '고요';
UPDATE players SET soop_id = 'arr0530', profile_image = '//profile.img.sooplive.co.kr/LOGO/ar/arr0530/arr0530.jpg' WHERE nickname = '권아온';
UPDATE players SET soop_id = 'fidfidfid', profile_image = '//profile.img.sooplive.co.kr/LOGO/fi/fidfidfid/fidfidfid.jpg' WHERE nickname = '박쭈이';
UPDATE players SET soop_id = 'chuwari13', profile_image = '//profile.img.sooplive.co.kr/LOGO/ch/chuwari13/chuwari13.jpg' WHERE nickname = '요정너구리';
UPDATE players SET soop_id = 'qwer1317', profile_image = '//profile.img.sooplive.co.kr/LOGO/qw/qwer1317/qwer1317.jpg' WHERE nickname = '으니';
UPDATE players SET soop_id = 'a4s5kzg7wmk', profile_image = '//profile.img.sooplive.co.kr/LOGO/a4/a4s5kzg7wmk/a4s5kzg7wmk.jpg' WHERE nickname = '멍라희';
UPDATE players SET soop_id = 'dustntn53', profile_image = '//profile.img.sooplive.co.kr/LOGO/du/dustntn53/dustntn53.jpg' WHERE nickname = '옥수수';
UPDATE players SET soop_id = 'ktulsun00', profile_image = '//profile.img.sooplive.co.kr/LOGO/kt/ktulsun00/ktulsun00.jpg' WHERE nickname = '유녜';
UPDATE players SET soop_id = 'wegogin7410', profile_image = '//profile.img.sooplive.co.kr/LOGO/we/wegogin7410/wegogin7410.jpg' WHERE nickname = '있찌';
UPDATE players SET soop_id = 'hamhee', profile_image = '//profile.img.sooplive.co.kr/LOGO/ha/hamhee/hamhee.jpg' WHERE nickname = '햄희';
UPDATE players SET soop_id = 'kaudwnd52', profile_image = '//profile.img.sooplive.co.kr/LOGO/ka/kaudwnd52/kaudwnd52.jpg' WHERE nickname = '밍둥이';
UPDATE players SET soop_id = 'xx00uxx', profile_image = '//profile.img.sooplive.co.kr/LOGO/xx/xx00uxx/xx00uxx.jpg' WHERE nickname = '윤하랑';
UPDATE players SET soop_id = 'rofvmtm', profile_image = '//profile.img.sooplive.co.kr/LOGO/ro/rofvmtm/rofvmtm.jpg' WHERE nickname = '짜미';
UPDATE players SET soop_id = 'yuna1024', profile_image = '//profile.img.sooplive.co.kr/LOGO/yu/yuna1024/yuna1024.jpg' WHERE nickname = '김유나';
UPDATE players SET soop_id = 's1on0106', profile_image = '//profile.img.sooplive.co.kr/LOGO/s1/s1on0106/s1on0106.jpg' WHERE nickname = '김쵸아';
UPDATE players SET soop_id = 'yeonvelyo3o', profile_image = '//profile.img.sooplive.co.kr/LOGO/ye/yeonvelyo3o/yeonvelyo3o.jpg' WHERE nickname = '이영숙';
UPDATE players SET soop_id = 'sr629', profile_image = '//profile.img.sooplive.co.kr/LOGO/sr/sr629/sr629.jpg' WHERE nickname = '사랑e';
UPDATE players SET soop_id = 'dlwjddls30', profile_image = '//profile.img.sooplive.co.kr/LOGO/dl/dlwjddls30/dlwjddls30.jpg' WHERE nickname = '땃쥐';
UPDATE players SET soop_id = 'qpqpro', profile_image = '//profile.img.sooplive.co.kr/LOGO/qp/qpqpro/qpqpro.jpg' WHERE nickname = '디임';
UPDATE players SET soop_id = 'ouo20411', profile_image = '//profile.img.sooplive.co.kr/LOGO/ou/ouo20411/ouo20411.jpg' WHERE nickname = '히댕';
UPDATE players SET soop_id = '1004yomi', profile_image = '//profile.img.sooplive.co.kr/LOGO/10/1004yomi/1004yomi.jpg' WHERE nickname = '단솔';
UPDATE players SET soop_id = 'saaaaa1212', profile_image = '//profile.img.sooplive.co.kr/LOGO/sa/saaaaa1212/saaaaa1212.jpg' WHERE nickname = '농떼르만';
UPDATE players SET soop_id = 'ndudska620', profile_image = '//profile.img.sooplive.co.kr/LOGO/nd/ndudska620/ndudska620.jpg' WHERE nickname = '김영주';

-- ─── 인덱스 ───
CREATE INDEX IF NOT EXISTS idx_players_soop_id ON players(soop_id);

COMMIT;
